train:
  epoch: 10
  batch: 128
  lr: 0.001
  num_workers: 4
  save_interval: 5
  iter: -1
  schedule-step: 0
  schedule-rate: 0.1
  time-window: 100

model:
  type: "deltasnn"
  in_features: 784
  hidden_size: 300
  out_features: 2
  beta1: 0.95
  beta2: 0.95
  num_steps: 10
  dropout: 0.1
  output-membrane: false
  spike-grad: atan

  delta-threshold: 0.01
  learnable-threshold: true
  learnable_delta_threshold: true 
